#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Script to print ident(1) tags from files/directories $
# $Copyright: 2016-2018 Devin Teske. All rights reserved. $
# $FrauBSD: pident/pident 2018-11-29 02:16:57 -0800 freebsdfrau $
#
############################################################ GLOBALS

pgm="${0##*/}" # Program basename

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Command-line options
#
KEYWORD=	# -k name
UNIQUE=		# -u
HIDE_NAME=	# -n

############################################################ FUNCTIONS

usage()
{
	echo "Usage: $pgm [-nu] [-k name] path ..." >&2
	exit $FAILURE
}

exec 9<<'EOF'
match($0, /\$[[:alnum:]_]+: [^$]* \$/) {
	if (!hide_name) printf "%s ", substr(FILENAME, trim + 1)
	print substr($0, RSTART, RLENGTH)
}
EOF
pident_awk=$( cat <&9 )
pident_find()
{
	local trim=0
	case "$1" in
	-) set -- /dev/stdin ;;
	-*) set -- "./$1"; trim=2 ;;
	esac
	exec 9<&0
	export HIDE_NAME pident_awk trim
	find "$1" -print0 ! -type d \
		! -path '*/CVS/*' \
		! -path '*/.svn/*' \
		! -path '*/.git/*' \
		| xargs -0 sh -c 'awk \
			-v hide_name=$HIDE_NAME \
			-v trim=$trim \
			"$pident_awk" "$@" 0<&9
		' sh
}

############################################################ MAIN

#
# Process command-line options
#
while getopts k:nu flag; do
	case "$flag" in
	k) KEYWORD="$OPTARG" ;;
	n) HIDE_NAME=1 ;;
	u) UNIQUE=1 ;;
	*) usage # NOTREACHED
	esac
done
shift $(( $OPTIND - 1 ))

[ $# -gt 0 ] || usage # NOTREACHED

#
# Process command-line arguments
#
while [ $# -gt 0 ]; do
	pident_find "$1"
	shift
done | {
	if [ ! "$UNIQUE$KEYWORD" ]; then
		cat
		exit $SUCCESS
	fi
	{ if [ "$UNIQUE" -a ! "$HIDE_NAME" ]; then
	  	cut -d ' ' -f2-
	  else
	  	cat
	  fi
	} | grep "\\$\\(${KEYWORD:-.*}\\): " | sort | {
		if [ ! "$UNIQUE" ]; then
			cat
			exit $SUCCESS
		fi
		uniq -c
	}
	exit $SUCCESS
}

################################################################################
# END
################################################################################
